"""PDF, Excel and CSV generation. Every function returns bytes for st.download_button."""
import io
from xml.sax.saxutils import escape

import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

import config
from services.report_service import ReportData, trace_chain
from services.traceability_service import TraceResult
from utils.dates import to_display

CONE_COLUMNS = ["Yarn Cone ID", "Autoconer", "Drum", "Cone Scan Date & Time"]
COB_COLUMNS = ["COB ID", "Speedframe", "Spindle", "COB Scan Date & Time"]
CSV_COLUMNS = ["Searched Type", "Searched ID", "Status", *CONE_COLUMNS, *COB_COLUMNS]
HEADER_FILL = colors.HexColor("#dbe7f6")


def file_stem(report: ReportData) -> str:
    return f"traceability_{report.trace.searched_id}_{report.generated_at:%Y%m%d_%H%M%S}"


def _cone_values(trace: TraceResult) -> list[str]:
    c = trace.cone
    return [c.cy_id, c.autoconer_id, c.drum_id, to_display(c.cone_scan_datetime)] if c else [""] * 4


def _cob_rows(trace: TraceResult) -> list[list[str]]:
    return [[c.cob_id, c.speedframe_id, c.spindle_id, to_display(c.cob_scan_datetime)] for c in trace.cobs]


def _header_pairs(report: ReportData) -> list[tuple[str, str]]:
    t = report.trace
    return [
        ("Searched", f"{t.searched_type} {t.searched_id}"),
        ("Status", t.status),
        ("Generated At", to_display(report.generated_at)),
        ("Generated By", report.generated_by),
        ("Reference No", report.reference_no),
    ]


# --- CSV -------------------------------------------------------------------------
def to_csv(report: ReportData) -> bytes:
    t = report.trace
    lead = [t.searched_type, t.searched_id, t.status, *_cone_values(t)]
    rows = [lead + cob for cob in _cob_rows(t)] or [lead + [""] * len(COB_COLUMNS)]
    return pd.DataFrame(rows, columns=CSV_COLUMNS).to_csv(index=False).encode("utf-8-sig")


# --- Excel -----------------------------------------------------------------------
def to_excel(report: ReportData) -> bytes:
    t = report.trace
    summary = [("Report Title", report.title), *_header_pairs(report),
               *zip(CONE_COLUMNS, _cone_values(t)),
               ("Traceability", trace_chain(t)),
               ("System", f"{config.APP_NAME} v{config.APP_VERSION}"),
               ("Report Version", config.REPORT_VERSION)]
    cobs = [[i, *row] for i, row in enumerate(_cob_rows(t), start=1)]
    buffer = io.BytesIO()
    with pd.ExcelWriter(buffer, engine="openpyxl") as writer:
        pd.DataFrame(summary, columns=["Field", "Value"]).to_excel(writer, sheet_name="Summary", index=False)
        pd.DataFrame(cobs, columns=["Sl. No.", *COB_COLUMNS]).to_excel(writer, sheet_name="COBs", index=False)
        pd.DataFrame({"Exception": t.exceptions or ["None"]}).to_excel(writer, sheet_name="Exceptions", index=False)
    return buffer.getvalue()


# --- PDF -------------------------------------------------------------------------
def _table(data: list[list[str]], header_row: bool) -> Table:
    table = Table(data, hAlign="LEFT")
    style = [("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
             ("FONTSIZE", (0, 0), (-1, -1), 9),
             ("VALIGN", (0, 0), (-1, -1), "MIDDLE")]
    if header_row:
        style += [("BACKGROUND", (0, 0), (-1, 0), HEADER_FILL), ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold")]
    else:
        style += [("BACKGROUND", (0, 0), (0, -1), HEADER_FILL), ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold")]
    table.setStyle(TableStyle(style))
    return table


def to_pdf(report: ReportData) -> bytes:
    t = report.trace
    styles = getSampleStyleSheet()
    body, h2 = styles["BodyText"], styles["Heading2"]
    story = [Paragraph(escape(report.title), styles["Title"]),
             _table([list(p) for p in _header_pairs(report)], header_row=False),
             Spacer(1, 6 * mm),
             Paragraph("Cone Information", h2)]
    story.append(_table([CONE_COLUMNS, _cone_values(t)], header_row=True) if t.cone
                 else Paragraph("No linked Yarn Cone.", body))
    story.append(Paragraph("COB Information", h2))
    story.append(_table([["Sl. No.", *COB_COLUMNS]] + [[str(i), *r] for i, r in enumerate(_cob_rows(t), start=1)],
                        header_row=True) if t.cobs else Paragraph("No COBs.", body))
    story.append(Paragraph("Traceability", h2))
    story.append(Paragraph(escape(trace_chain(t, arrow="->")), body))  # Helvetica has no "→" glyph
    story.append(Paragraph("Exceptions", h2))
    story.extend(Paragraph("• " + escape(e), body) for e in t.exceptions)
    if not t.exceptions:
        story.append(Paragraph("None", body))

    def footer(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.drawString(15 * mm, 10 * mm,
                          f"{config.APP_NAME} | Report v{config.REPORT_VERSION} | Ref {report.reference_no}")
        canvas.drawRightString(A4[0] - 15 * mm, 10 * mm, f"Page {doc.page}")
        canvas.restoreState()

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, title=report.title, author=report.generated_by,
                            leftMargin=15 * mm, rightMargin=15 * mm, topMargin=15 * mm, bottomMargin=20 * mm)
    doc.build(story, onFirstPage=footer, onLaterPages=footer)
    return buffer.getvalue()
